### ISSUE TITLE
Add Racket (DrRacket)

### ISSUE THREAD

**Issue by MrEvilOnGitHub** [engineer-man/piston#386] opened 2021-10-20 17:36 UTC
Runtime installer can be found [here](https://download.racket-lang.org/)
Why Racket?
I don't know about other Universities, but at mine it is used as the introduction language for programming and I and a few others are working on an OSS [Discord bot](https://github.com/MrEvilOnGitHub/Info2-Bot-Inofficial-) that provides different features that are designed to help CS students, including the execution of small code-bits through the use of this project. Adding Racket to the list of supported languages would greatly help us to help our fellow students with their questions.

**Comment by zachspar** [comment] 2021-11-01 04:36
This seems like a duplicate of #208.

**Comment by HexF** [comment] 2021-11-04 09:44
Duplicate as above

**Closed by HexF** 2021-11-04 09:44 UTC
Labels: package
